// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAupJ6h3LynM2lU4jCmSKDTS5ZgsKv-3U8',
    appId: '1:389813741089:web:78980126404f98da876560',
    messagingSenderId: '389813741089',
    projectId: 'uiren-33b03',
    authDomain: 'uiren-33b03.firebaseapp.com',
    storageBucket: 'uiren-33b03.firebasestorage.app',
    measurementId: 'G-W3DW1HKH8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUJjEb9XYT9YAU1ntys7F3TYk-zngoCUw',
    appId: '1:389813741089:android:c8eb9c8cbf11355a876560',
    messagingSenderId: '389813741089',
    projectId: 'uiren-33b03',
    storageBucket: 'uiren-33b03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAesPqJYupvpJotqI481XwRaZGFsbyYMXI',
    appId: '1:389813741089:ios:d445d75956412e55876560',
    messagingSenderId: '389813741089',
    projectId: 'uiren-33b03',
    storageBucket: 'uiren-33b03.firebasestorage.app',
    iosBundleId: 'com.example.uiren',
  );
}
